#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	2
bspc config window_gap          	4
bspc config top_padding				20
bspc config bottom_padding			20
bspc config left_padding 			0
bspc config right_padding 			0

bspc config normal_border_color 	#000000
bspc config active_border_color 	#ffffff
bspc config focused_border_color 	#ffffff

bspc config click_to_focus 			true


bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


nm-applet &
picom &
flameshot &
dunst &

