#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitors
bspc wm -O %DP-0.8 HDMI-0
bspc monitor %DP-0.8 -d 1 2 3 4 5 6 7 8
bspc monitor HDMI-0 -d 9 10

# Borders and gaps
bspc config border_width         	2
bspc config window_gap          	10
bspc config top_padding				20
bspc config bottom_padding			0
bspc config left_padding 			0
bspc config right_padding 			0

# Colors
bspc config normal_border_color 	$(xrdb -query | grep "*.background" | cut -f 2)
bspc config active_border_color 	$(xrdb -query | grep "*.background" | cut -f 2)
bspc config focused_border_color 	$(xrdb -query | grep "*.foreground" | cut -f 2)

# Misc settings
bspc config click_to_focus 			true
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config	ignore_ewmh_focus		true

# Rules for specific programs
bspc rule -a discord desktop='^10'
bspc rule -a obsidian desktop='^9'
bspc rule -a Spotify desktop='^10' follow=false
# TODO

# Startup background apps and default apps
nm-applet &
picom --frame-opacity $(xrdb -query | grep "borderOpacity" | cut -f 2) &
flameshot &
dunst &
spotify &
discord &
obsidian &
# The sleep is needed to prevent polybar from loading before bspwm, causing problems.
(sleep 0.5;$HOME/.config/polybar/shapes/launch.sh) &

# Focus desktop 10, then 1. This is needed to default to 10 instead of 10 for my side monitor.
bspc desktop -f 10
bspc desktop -f 1
