#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Borders and gaps
bspc config border_width         	1
bspc config window_gap          	10
bspc config top_padding				20
bspc config bottom_padding			0
bspc config left_padding 			0
bspc config right_padding 			0

# Colors
bspc config normal_border_color 	#000000
bspc config active_border_color 	#ffffff
bspc config focused_border_color 	#ffffff

# Misc settings
bspc config click_to_focus 			true
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

# Rules for specific programs
# TODO

# Startup background apps
nm-applet &
picom &
flameshot &
dunst &
$HOME/.config/polybar/shapes/launch.sh &
